// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smjjpxhgnomucvmmllaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtampweGhnbm9tdWN2bW1sbGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NjM2NTYsImV4cCI6MjA4NTEzOTY1Nn0.Xdtz-PTzKQt49E2e4glrFJKS9hK6HAbJ5NOZr9KjN3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});